export enum ShoesType {
  MEN = "men",
  WOMEN = "women",
}

export const defaultShoes = [
  {
    id: 0,
    price: 149.99,
    title: "Nike Air Max 1",
    url: "https://static.footshop.com/740440-full_product/171394.jpg",
    wish: false,
    type: ShoesType.MEN,
  },
  {
    id: 1,
    price: 110.0,
    title: "Adidas  Forum 84 Low",
    url: "https://static.footshop.com/752146-full_product/192808.jpg",
    wish: false,
    type: ShoesType.MEN,
  },
  {
    id: 2,
    price: 100.0,
    title: "Adidas Terrex Voyager 21",
    url: "https://static.footshop.com/759853-full_product/193795.jpg",
    wish: false,
    type: ShoesType.MEN,
  },
  {
    id: 3,
    price: 110.0,
    title: "Adidas  Forum 84 Low",
    url: "https://static.footshop.com/752146-full_product/192808.jpg",
    wish: false,
    type: ShoesType.WOMEN,
  },
  {
    id: 4,
    price: 149.99,
    title: "Nike Air Max 1",
    url: "https://static.footshop.com/740440-full_product/171394.jpg",
    wish: false,
    type: ShoesType.WOMEN,
  },
  {
    id: 5,
    price: 110.0,
    title: "Adidas  Forum 84 Low",
    url: "https://static.footshop.com/752146-full_product/192808.jpg",
    wish: false,
    type: ShoesType.WOMEN,
  },
  {
    id: 6,
    price: 149.99,
    title: "Nike Air Max 1",
    url: "https://static.footshop.com/740440-full_product/171394.jpg",
    wish: false,
    type: ShoesType.WOMEN,
  },
  {
    id: 7,
    price: 100.0,
    title: "Adidas Terrex Voyager 21",
    url: "https://static.footshop.com/759853-full_product/193795.jpg",
    wish: false,
    type: ShoesType.MEN,
  },
  {
    id: 8,
    price: 149.99,
    title: "Nike Air Max 1",
    url: "https://static.footshop.com/740440-full_product/171394.jpg",
    wish: false,
    type: ShoesType.MEN,
  },
  {
    id: 9,
    price: 110.0,
    title: "Adidas  Forum 84 Low",
    url: "https://static.footshop.com/752146-full_product/192808.jpg",
    wish: false,
    type: ShoesType.MEN,
  },
  {
    id: 10,
    price: 100.0,
    title: "Adidas Terrex Voyager 21",
    url: "https://static.footshop.com/759853-full_product/193795.jpg",
    wish: false,
    type: ShoesType.WOMEN,
  },
  {
    id: 11,
    price: 110.0,
    title: "Adidas  Forum 84 Low",
    url: "https://static.footshop.com/752146-full_product/192808.jpg",
    wish: false,
    type: ShoesType.WOMEN,
  },
  {
    id: 12,
    price: 149.99,
    title: "Nike Air Max 1",
    url: "https://static.footshop.com/740440-full_product/171394.jpg",
    wish: false,
    type: ShoesType.WOMEN,
  },
  {
    id: 13,
    price: 110.0,
    title: "Adidas  Forum 84 Low",
    url: "https://static.footshop.com/752146-full_product/192808.jpg",
    wish: false,
    type: ShoesType.MEN,
  },
];

export const sizes = {
  eu: {
    region: "eu",
    size: [
      { id: 0, size: 38 },
      { id: 1, size: 39 },
      { id: 2, size: 40 },
      { id: 3, size: 41 },
      { id: 4, size: 42 },
      { id: 5, size: 43 },
      { id: 6, size: 44 },
      { id: 7, size: 45 },
      { id: 8, size: 46 },
    ],
  },

  us: {
    region: "us",
    size: [
      { id: 0, size: 8 },
      { id: 1, size: 8.5 },
      { id: 2, size: 9 },
      { id: 3, size: 9.5 },
      { id: 4, size: 10 },
      { id: 5, size: 10.5 },
      { id: 6, size: 11 },
      { id: 7, size: 11.5 },
      { id: 8, size: 12 },
    ],
  },
};
